In [26]:
import os

In [27]:
os.getcwd()

'C:\\Users\\dhvani'

In [28]:
path="C:\\Users\\dhvani\\train.csv"

In [59]:
import pandas as pd

In [60]:
#allfiles = glob.glob(path+"/*.csv")

In [61]:
#allfiles

In [62]:
df = pd.read_csv('train.csv')

In [63]:
df

Unnamed: 0  Borivali  Andheri  Bandra  Dadar  Churchgate class
0            0       140        3      41    153          63  DBCC
1            1       102       38     224      7          29  bbBC
2            2        37      134      86    125          18  ADbC
3            3        57       19     160     35         129  bCCC
4            4        70        4      91     89         146  CCDC
5            5       146      101      18     69          66  BACC
6            6         1      214     146     38           1  AbAC
7            7       105       20     190      3          82  BbCC
8            8        48       32     157     23         140  bCCC
9            9        50       28      26     27         269  CCCb
10          10        26        8     125     90         151  CbCC
11          11       226       22      93     37          22  BBDC
12          12       113       88     139     24          36  bBBC
13          13       134       85      41     67          73  BbCC
14          14       165       90      50     71          24  BbCb
15          15       187       68       4    116          25  BDAC
16          16        21       24     218    115          22  bbDC
17          17        95      189      26     40          50  AAbC
18          18        91      131     101     49          28  AbAC
19          19        78       70       2     99         151  CCAC
20          20       139      102      90     56          13  BAbC
21          21        56       27     159     62          96  bDCA
22          22        28       41     188     39         104  bCCA
23          23        40       23     140     36         161  bCCA
24          24        26      127       5     46         196  CCAD
25          25       132       33     109     55          71  BbbC
26          26       267        7       6     71          49  BBDC
27          27        73      169      20    105          33  ADDC
28          28         3      120      24    137         116  DCCA
29          29        51      116      29     20         184  CCAb
30          30       141       34      64     72          89  BCDD
31          31       122      114      19     84          61  BADC
32          32        92      130      52     30          96  ACDB
33          33        85      221       1     36          57  AABC
34          34        82       81      63     14         160  CCbA
35          35        64        4     212      8         112  BBCC
36          36       178       75       6     15         126  BACC
37          37       117       10       3    250          20  DDCB
38          38         7       89      99    156          49  DCbA
39          39        13       94     138      6         149  CCbA
40          40        26      135     113     84          42  AbDC
41          41        64       26      23    153         134  DCCb
42          42         1      154      27     32         186  CAAD
43          43       214       45      29    101          11  BBDC
44          44         9      149     199      7          36  bbAC
45          45       149       80      47     40          84  BCAD
46          46         4        1      25    183         187  CCDD
47          47       112       67      84     90          47  BDDC
48          48       136        1     190     34          39  bBBC
49          49        93       77     133      6          91  bBDC
50          50        68       75     131     40          86  bCbC
51          51        28       30     179     47         116  bCCD
52          52       136        6     128     22         108  BCbA
53          53        85        4      71    131         109  DCbB
54          54        15       56     221      4         104  bCAB
55          55       153       80     137     20          10  bBDA
56          56        44       10      25    217         104  DCBb
57          57        93       76      14     13         204  CCCD
58          58        63       40      44     88   

In [64]:
df = pd.read_csv("train.csv",index_col=0)

In [65]:
df.head() #borivali=B

Borivali  Andheri  Bandra  Dadar  Churchgate class
0       140        3      41    153          63  DBCC
1       102       38     224      7          29  bbBC
2        37      134      86    125          18  ADbC
3        57       19     160     35         129  bCCC
4        70        4      91     89         146  CCDC

In [66]:
df.tail()

Borivali  Andheri  Bandra  Dadar  Churchgate class
55       153       80     137     20          10  bBDA
56        44       10      25    217         104  DCBb
57        93       76      14     13         204  CCCD
58        63       40      44     88         165  CCBb
59        31       25     200    111          33  bbDC

In [67]:
df[0:5]  #works for rows

Borivali  Andheri  Bandra  Dadar  Churchgate class
0       140        3      41    153          63  DBCC
1       102       38     224      7          29  bbBC
2        37      134      86    125          18  ADbC
3        57       19     160     35         129  bCCC
4        70        4      91     89         146  CCDC

In [68]:
df.loc[:,['Borivali','Andheri']] #rows of speicific columns. columns names should be mentioned
#df.loc[0:5, 0:2]

Borivali  Andheri
0        140        3
1        102       38
2         37      134
3         57       19
4         70        4
5        146      101
6          1      214
7        105       20
8         48       32
9         50       28
10        26        8
11       226       22
12       113       88
13       134       85
14       165       90
15       187       68
16        21       24
17        95      189
18        91      131
19        78       70
20       139      102
21        56       27
22        28       41
23        40       23
24        26      127
25       132       33
26       267        7
27        73      169
28         3      120
29        51      116
30       141       34
31       122      114
32        92      130
33        85      221
34        82       81
35        64        4
36       178       75
37       117       10
38         7       89
39        13       94
40        26      135
41        64       26
42         1      154
43       214       45
44         9      149
45       149       80
46         4        1
47       112       67
48       136        1
49        93       77
50        68       75
51        28       30
52       136        6
53        85        4
54        15       56
55       153       80
56        44       10
57        93       76
58        63       40
59        31       25

In [69]:
df.iloc[0:5,0:2]  #column names should not be mentioned

Borivali  Andheri
0       140        3
1       102       38
2        37      134
3        57       19
4        70        4

In [70]:
df1 = df[:40]   #training data

In [71]:
df1.tail()

Borivali  Andheri  Bandra  Dadar  Churchgate class
35        64        4     212      8         112  BBCC
36       178       75       6     15         126  BACC
37       117       10       3    250          20  DDCB
38         7       89      99    156          49  DCbA
39        13       94     138      6         149  CCbA

In [72]:
df2 = df[40:]   #test data

In [73]:
df2

Borivali  Andheri  Bandra  Dadar  Churchgate class
40        26      135     113     84          42  AbDC
41        64       26      23    153         134  DCCb
42         1      154      27     32         186  CAAD
43       214       45      29    101          11  BBDC
44         9      149     199      7          36  bbAC
45       149       80      47     40          84  BCAD
46         4        1      25    183         187  CCDD
47       112       67      84     90          47  BDDC
48       136        1     190     34          39  bBBC
49        93       77     133      6          91  bBDC
50        68       75     131     40          86  bCbC
51        28       30     179     47         116  bCCD
52       136        6     128     22         108  BCbA
53        85        4      71    131         109  DCbB
54        15       56     221      4         104  bCAB
55       153       80     137     20          10  bBDA
56        44       10      25    217         104  DCBb
57        93       76      14     13         204  CCCD
58        63       40      44     88         165  CCBb
59        31       25     200    111          33  bbDC

In [74]:
data = df1.ix[:,:-1]

In [75]:
data.head()

Borivali  Andheri  Bandra  Dadar  Churchgate
0       140        3      41    153          63
1       102       38     224      7          29
2        37      134      86    125          18
3        57       19     160     35         129
4        70        4      91     89         146

In [76]:
label = df1.ix[:,-1:]   

In [77]:
label.head()

class
0  DBCC
1  bbBC
2  ADbC
3  bCCC
4  CCDC

In [78]:
type(label)

pandas.core.frame.DataFrame

In [79]:
#data= data.as_matrix()     # converting dataframe into array

In [80]:
#type(data)

In [81]:
data = data.values

In [82]:
type(data)

numpy.ndarray

In [83]:
label = label.values

In [84]:
label

array([['DBCC'],
       ['bbBC'],
       ['ADbC'],
       ['bCCC'],
       ['CCDC'],
       ['BACC'],
       ['AbAC'],
       ['BbCC'],
       ['bCCC'],
       ['CCCb'],
       ['CbCC'],
       ['BBDC'],
       ['bBBC'],
       ['BbCC'],
       ['BbCb'],
       ['BDAC'],
       ['bbDC'],
       ['AAbC'],
       ['AbAC'],
       ['CCAC'],
       ['BAbC'],
       ['bDCA'],
       ['bCCA'],
       ['bCCA'],
       ['CCAD'],
       ['BbbC'],
       ['BBDC'],
       ['ADDC'],
       ['DCCA'],
       ['CCAb'],
       ['BCDD'],
       ['BADC'],
       ['ACDB'],
       ['AABC'],
       ['CCbA'],
       ['BBCC'],
       ['BACC'],
       ['DDCB'],
       ['DCbA'],
       ['CCbA']], dtype=object)

In [85]:
from sklearn.linear_model import LogisticRegression

In [89]:
label = label.reshape(40,)

In [90]:
label

array(['DBCC', 'bbBC', 'ADbC', 'bCCC', 'CCDC', 'BACC', 'AbAC', 'BbCC',
       'bCCC', 'CCCb', 'CbCC', 'BBDC', 'bBBC', 'BbCC', 'BbCb', 'BDAC',
       'bbDC', 'AAbC', 'AbAC', 'CCAC', 'BAbC', 'bDCA', 'bCCA', 'bCCA',
       'CCAD', 'BbbC', 'BBDC', 'ADDC', 'DCCA', 'CCAb', 'BCDD', 'BADC',
       'ACDB', 'AABC', 'CCbA', 'BBCC', 'BACC', 'DDCB', 'DCbA', 'CCbA'], dtype=object)

In [98]:
da = data.reshape(40,5,)

In [99]:
da

array([[140,   3,  41, 153,  63],
       [102,  38, 224,   7,  29],
       [ 37, 134,  86, 125,  18],
       [ 57,  19, 160,  35, 129],
       [ 70,   4,  91,  89, 146],
       [146, 101,  18,  69,  66],
       [  1, 214, 146,  38,   1],
       [105,  20, 190,   3,  82],
       [ 48,  32, 157,  23, 140],
       [ 50,  28,  26,  27, 269],
       [ 26,   8, 125,  90, 151],
       [226,  22,  93,  37,  22],
       [113,  88, 139,  24,  36],
       [134,  85,  41,  67,  73],
       [165,  90,  50,  71,  24],
       [187,  68,   4, 116,  25],
       [ 21,  24, 218, 115,  22],
       [ 95, 189,  26,  40,  50],
       [ 91, 131, 101,  49,  28],
       [ 78,  70,   2,  99, 151],
       [139, 102,  90,  56,  13],
       [ 56,  27, 159,  62,  96],
       [ 28,  41, 188,  39, 104],
       [ 40,  23, 140,  36, 161],
       [ 26, 127,   5,  46, 196],
       [132,  33, 109,  55,  71],
       [267,   7,   6,  71,  49],
       [ 73, 169,  20, 105,  33],
       [  3, 120,  24, 137, 116],
       [ 51, 1

In [100]:
model = LogisticRegression()

In [101]:
model.fit(data, label)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [104]:
model.predict([[25,100,100,75,100]])

array(['BbCC'], dtype=object)

In [105]:
model.predict([[25,100,100,75,100]])[0] #logistic regression

'BbCC'

In [106]:
from sklearn.externals import joblib

In [107]:
joblib.dump(model,'logre.pkl')

['logre.pkl']

In [108]:
model2 = joblib.load('logre.pkl')

In [109]:
model2.predict([[25,100,100,75,100]])[0]

'BbCC'

In [43]:
from sklearn.naive_bayes import GaussianNB 

In [44]:
model1 = GaussianNB()

In [45]:
model1.fit(data, label)

GaussianNB(priors=None)

In [46]:
model1.predict([[25,100,100,75,100]])[0]

'BbCC'

In [118]:
data2 = df2.ix[:,:-1]

In [119]:
label2 = df2.ix[:,-1:]

In [120]:
label2

class
40  AbDC
41  DCCb
42  CAAD
43  BBDC
44  bbAC
45  BCAD
46  CCDD
47  BDDC
48  bBBC
49  bBDC
50  bCbC
51  bCCD
52  BCbA
53  DCbB
54  bCAB
55  bBDA
56  DCBb
57  CCCD
58  CCBb
59  bbDC

In [121]:
data2 = data2.values

In [122]:
label2 = label2.values

In [123]:
expected = label2

In [124]:
predicted=model.predict(data2)

In [125]:
predicted

array(['BbCC', 'CbCC', 'CCAD', 'BAbC', 'AbAC', 'BbCC', 'CbCC', 'BbCC',
       'DBCC', 'CCbA', 'BbCC', 'bCCA', 'BbCC', 'CCDC', 'bCCA', 'AbAC',
       'CbCC', 'CCbA', 'BCDD', 'bbDC'], dtype=object)

In [126]:
len(predicted)

20

In [127]:
expected

array([['AbDC'],
       ['DCCb'],
       ['CAAD'],
       ['BBDC'],
       ['bbAC'],
       ['BCAD'],
       ['CCDD'],
       ['BDDC'],
       ['bBBC'],
       ['bBDC'],
       ['bCbC'],
       ['bCCD'],
       ['BCbA'],
       ['DCbB'],
       ['bCAB'],
       ['bBDA'],
       ['DCBb'],
       ['CCCD'],
       ['CCBb'],
       ['bbDC']], dtype=object)

In [130]:
a = 0
for i, j in zip(expected, predicted):
    if i == j:
        a = a + 1
        print(a)

1


In [87]:
[i for i, j in zip(expected, predicted) if i == j]

[array(['bbDC'], dtype=object)]

In [57]:
from sklearn import model_selection

In [58]:
seed = 7
scoring = "accuracy"
models = LogisticRegression()
kfold = model_selection.KFold(n_splits=10, random_state=seed)
cv_results = model_selection.cross_val_score(models, data, label, cv=kfold, scoring=scoring)
print(cv_results.mean(), cv_results.std())

0.075 0.114564392374


In [62]:
from sklearn.metrics import accuracy_score

In [63]:
print(accuracy_score(expected, predicted))

0.05


In [85]:
from sklearn import metrics

In [86]:
print(metrics.classification_report(expected, predicted))

             precision    recall  f1-score   support

       AbAC       0.00      0.00      0.00         0
       AbDC       0.00      0.00      0.00         1
       BAbC       0.00      0.00      0.00         0
       BBDC       0.00      0.00      0.00         1
       BCAD       0.00      0.00      0.00         1
       BCDD       0.00      0.00      0.00         0
       BCbA       0.00      0.00      0.00         1
       BDDC       0.00      0.00      0.00         1
       BbCC       0.00      0.00      0.00         0
       CAAD       0.00      0.00      0.00         1
       CCAD       0.00      0.00      0.00         0
       CCBb       0.00      0.00      0.00         1
       CCCD       0.00      0.00      0.00         1
       CCDC       0.00      0.00      0.00         0
       CCDD       0.00      0.00      0.00         1
       CCbA       0.00      0.00      0.00         0
       CbCC       0.00      0.00      0.00         0
       DBCC       0.00      0.00      0.00   

c:\users\dhvani\appdata\local\programs\python\python35\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
c:\users\dhvani\appdata\local\programs\python\python35\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [98]:
print(metrics.confusion_matrix(expected, predicted))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [145]:
from sklearn.svm import SVC

In [146]:
model2 = SVC()

In [152]:
classifier=model2.fit(data, label)

c:\users\rajan jha\appdata\local\programs\python\python35\lib\site-packages\sklearn\utils\validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [153]:
classifier.predict([140, 160 ,50, 25 ,25])[0]

c:\users\rajan jha\appdata\local\programs\python\python35\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


'bCCC'

In [150]:
from sklearn import cPickle

ImportError: cannot import name 'cPickle'

In [151]:
import pickle

In [157]:
save_clf = open('classifier.pickle', 'wb')
pickle.dump(classifier, save_clf,protocol=2)
save_clf.close()

In [155]:
a=[124,150,50,25,25]

In [89]:
import tensorflow as tf

In [91]:
import tflearn

In [92]:
dataframe = pd.read_csv('abhishek.csv')


In [102]:
df.Borivali.unique

<bound method Series.unique of 0     140
1     102
2      37
3      57
4      70
5     146
6       1
7     105
8      48
9      50
10     26
11    226
12    113
13    134
14    165
15    187
16     21
17     95
18     91
19     78
20    139
21     56
22     28
23     40
24     26
25    132
26    267
27     73
28      3
29     51
30    141
31    122
32     92
33     85
34     82
35     64
36    178
37    117
38      7
39     13
40     26
41     64
42      1
43    214
44      9
45    149
46      4
47    112
48    136
49     93
50     68
51     28
52    136
53     85
54     15
55    153
56     44
57     93
58     63
59     31
Name: Borivali, dtype: int64>

In [103]:
print(__name__)

__main__


In [105]:
from tflearn.data_utils import load_csv

In [106]:
data,label = load_csv("abhishek.csv")